/*
  Cryptographically verify a message and signature was signed by a provided
  BCH address.
*/

// Global npm libraries

// Local libraries
import BchWallet from 'minimal-slp-wallet'
import { bindMethods } from '../lib/bind-methods.js'
import { validateRequiredFlags } from '../lib/flag-validator.js'

class MsgVerify {
  constructor () {
    // Encapsulate Dependencies

    // Bind 'this' object to all subfunctions.
    bindMethods(this, ['run', 'validateFlags', 'verify'])
  }

  async run (flags) {
    try {
      this.validateFlags(flags)

      // Initialize the wallet.
      this.bchWallet = new BchWallet()
      await this.bchWallet.walletInfoPromise

      // Sweep any BCH and tokens from the private key.
      const result = await this.verify(flags)

      console.log(`Message: ${flags.msg}`)
      console.log(`Signature: ${flags.sig}`)
      console.log(`Signature was generated by private key associated with address ${flags.addr}: ${result}`)

      return true
    } catch (err) {
      console.error('Error in msg-verify: ', err)
      return 0
    }
  }

  validateFlags (flags = {}) {
    return validateRequiredFlags([
      [flags.addr, 'You must specify an address with the -a flag.'],
      [flags.msg, 'You must specify a message to sign with the -m flag.'],
      [flags.sig, 'You must specify a signature with the -s flag.']
    ])
  }

  async verify (flags) {
    try {
      const result = this.bchWallet.bchjs.BitcoinCash.verifyMessage(
        flags.addr,
        flags.sig,
        flags.msg
      )

      return result
    } catch (err) {
      console.error('Error in verify()')
      throw err
    }
  }
}

export default MsgVerify

// mutate4javascript-manifest-begin
// {"version":1,"tested_at":"2026-10-08T14:48:05.712Z","module_hash":"5f9d883693fc8cf11628821dddfe949a81f3e41037d9d4b3c4a640b3d8aef103","functions":[{"id":"func/MsgVerify.constructor","name":"MsgVerify.constructor","line":14,"end_line":19,"hash":"ca9d2117f191d986b8a0188ee790d6140de1853c21bdc2a97b46169e4732f241"},{"id":"func/MsgVerify.run","name":"MsgVerify.run","line":21,"end_line":41,"hash":"d0ef59fcc21dd9c6a26e57eb754360915824d6eb0650f13d35b5b6f79efeea63"},{"id":"func/MsgVerify.validateFlags","name":"MsgVerify.validateFlags","line":43,"end_line":49,"hash":"9ec625c409f7b331222f182196fbb528cfc396ab26635380c42f2a3675e6dab2"},{"id":"func/MsgVerify.verify","name":"MsgVerify.verify","line":51,"end_line":64,"hash":"8f585e8604f3797a75b5ddca84ca7151738add59cc93e18f7f52019538624bc2"}]}
// mutate4javascript-manifest-end
