/*
  Cryptographically verify a message and signature was signed by a provided
  BCH address.
*/

// Global npm libraries

// Local libraries
import BchWallet from 'minimal-slp-wallet'

class MsgVerify {
  constructor () {
    // Encapsulate Dependencies

    // Bind 'this' object to all subfunctions.
    this.run = this.run.bind(this)
    this.validateFlags = this.validateFlags.bind(this)
    this.verify = this.verify.bind(this)
  }

  async run (flags) {
    try {
      this.validateFlags(flags)

      // Initialize the wallet.
      this.bchWallet = new BchWallet()
      await this.bchWallet.walletInfoPromise

      // Sweep any BCH and tokens from the private key.
      const result = await this.verify(flags)

      console.log(`Message: ${flags.msg}`)
      console.log(`Signature: ${flags.sig}`)
      console.log(`Signature was generated by private key associated with address ${flags.addr}: ${result}`)

      return true
    } catch (err) {
      console.error('Error in msg-sign: ', err)
      return 0
    }
  }

  validateFlags (flags = {}) {
    // Exit if address not specified.
    const addr = flags.addr
    if (!addr || addr === '') {
      throw new Error('You must specify an address with the -a flag.')
    }

    // Exit if wallet not specified.
    const msg = flags.msg
    if (!msg || msg === '') {
      throw new Error('You must specify a message to sign with the -m flag.')
    }

    // Exit if signature not specified.
    const sig = flags.sig
    if (!sig || sig === '') {
      throw new Error('You must specify a signature with the -s flag.')
    }

    return true
  }

  async verify (flags) {
    try {
      const result = this.bchWallet.bchjs.BitcoinCash.verifyMessage(
        flags.addr,
        flags.sig,
        flags.msg
      )

      return result
    } catch (err) {
      console.error('Error in verify()')
      throw err
    }
  }
}

export default MsgVerify

// mutate4javascript-manifest-begin
// {"version":1,"tested_at":"2026-10-06T22:18:14.495Z","module_hash":"ee3e2fc3e6df64e6b3c2f3b215732ff4eac4766857895fe459d2ecbd822da31a","functions":[{"id":"func/MsgVerify.constructor","name":"MsgVerify.constructor","line":12,"end_line":19,"hash":"5752cc02a13c4947510577cd10ca8afc6845c391d8ddf3b6917ed5fe7a53adb5"},{"id":"func/MsgVerify.run","name":"MsgVerify.run","line":21,"end_line":41,"hash":"d043b168e2bdc7c38f8b64bb39ea6e01921525c3ced000d56e773ac001085c7b"},{"id":"func/MsgVerify.validateFlags","name":"MsgVerify.validateFlags","line":43,"end_line":63,"hash":"7563acd49dbeda1eaedaabc37d9406882e08b4abea97b6201000d289ecad324e"},{"id":"func/MsgVerify.verify","name":"MsgVerify.verify","line":65,"end_line":78,"hash":"8f585e8604f3797a75b5ddca84ca7151738add59cc93e18f7f52019538624bc2"}]}
// mutate4javascript-manifest-end
